name: Lint on PR

on:
  pull_request:
    branches: [develop, 'feature/**', 'release/**']
  # Removed push trigger to prevent direct pushes to protected branches

# Set the permissions at the workflow level
permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate linting
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code style with ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Check formatting with Prettier
        id: prettier
        run: npx prettier --check .
        continue-on-error: true

      # Auto-fix and create PR if there are fixable issues
      - name: Try to fix ESLint issues
        if: github.event_name == 'pull_request' && (steps.eslint.outcome == 'failure' || steps.prettier.outcome == 'failure')
        id: fix
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm run lint:fix
          # Only create a commit if there are changes
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git add .
            git commit -m 'style: auto-fix ESLint and Prettier issues'
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with fixes
        if: github.event_name == 'pull_request' && steps.fix.outcome == 'success' && steps.fix.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: auto-fix ESLint and Prettier issues'
          title: 'style: auto-fix code style issues'
          body: 'Automated fixes for ESLint and Prettier issues. This PR was automatically generated by the CI/CD pipeline.'
          branch: fix/style-fixes-${{ github.event.pull_request.number }}
          base: ${{ github.event.pull_request.head.ref }}  # Use the PR branch as base
          delete-branch: true
          labels: 'style, automated'
          assignees: ${{ github.actor }}
          draft: false
          # Only add reviewers if this is not from a fork
          reviewers: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.actor || '' }}
          # Add a comment to the original PR
          comment-on-pr: true
          comment-mode: create
          comment-body: |
            I've created a PR with automatic style fixes for you to review. 
            
            **Changes made:**
            - Fixed ESLint issues
            - Fixed code formatting with Prettier
            
            Please review the changes and merge if everything looks good.
