name: Lint on PR

on:
  pull_request:
    branches: [develop, 'feature/**', 'release/**']

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for accurate linting
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check formatting with Prettier
        run: npx prettier --check .

      # Optional: Auto-fix and commit if there are fixable issues
      # - name: Try to fix ESLint issues
      #   run: npm run lint:fix
      # 
      # - name: Create Pull Request with fixes
      #   if: github.event_name == 'pull_request' && steps.fix.outcome == 'success' && steps.fix.outputs.has-changes == 'true'
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: 'style: auto-fix ESLint issues'
      #     title: 'style: auto-fix ESLint issues'
      #     body: 'Automated fixes for ESLint issues'
      #     branch: fix/eslint-issues-${{ github.event.pull_request.number }}
      #     base: ${{ github.head_ref }}
